#dcm_planner:
#    z_com: 0.9 #meter
#    step_time: 0.75 #second
#    step_size: 0.3 #meter
#    n_steps: 10
#    dt: 0.01 #second
#    contact_names: ["l_sole","r_sole"]
#    contact_sequence: [2, 1]
#    l_sole:
#        init_pose: [0.0,0.1,0.0,0.0,0.0,0.0,1.0]
#    r_sole:
#        init_pose: [0.0,-0.1,0.0,0.0,0.0,0.0,1.0]


dcm_planner:
    z_com: 0.9 #meter
    step_time: 0.75 #second
    step_size: 0.3 #meter
    n_steps: 12
    dt: 0.01 #second
    contact_names: ["lf_foot","rh_foot","rf_foot","lh_foot"]
    contact_sequence: [3, 4, 1, 2]
    lf_foot:
        init_pose: [0.3,0.3,0.0,0.0,0.0,0.0,1.0]
    rh_foot:
        init_pose: [-0.3,-0.3,0.0,0.0,0.0,0.0,1.0]
    rf_foot:
        init_pose: [0.3,-0.3,0.0,0.0,0.0,0.0,1.0]
    lh_foot:
        init_pose: [-0.3,0.3,0.0,0.0,0.0,0.0,1.0]
