dcm_planner:
    step_time: 0.75 #second
    step_size: 0.3 #meter
    n_steps: 12
    dt: 0.01 #second
    contact_names: ["lf_foot","rh_foot","rf_foot","lh_foot"]
    contact_sequence: [3, 4, 1, 2]
    contact_dimensions: [0.1] #radius
